#!/bin/zsh

SPDS=~/work/SPDSAPIModelDocumentation
AMDS=~/work/AMDSAPISwaggerModels
SPECDOCS=~/work/SpectrumDocs
STAGING=~/work/staging
SPAPID=~/work/selling-partner-api-docs
SPAPIM=~/work/selling-partner-api-models
UPGL=~/work/ParasolUsagePlanGenerationLambda

# pull AMDS
function pamds()
{
    cd $AMDS
    git checkout APIG
    git pull
    cd $OLDPWD
}

#pull Parasol
function pupgl() {
    cd $UPGL
    git pull
    cd $OLDPWD
}

# get from AMDS
function gamds()
{
    cd $AMDS/swagger-models
    echo 'Retrieved:'
    for file in `ls | grep "$1"`
    do
        echo "    - $file"
        cp $file $OLDPWD
    done
    cd $OLDPWD
}

# pull mainline branch of SpectrumDocs
function psd()
{
    cd $SPECDOCS
    BRANCH=`git rev-parse --abbrev-ref HEAD`
    git checkout mainline &> /dev/null
    git pull
    git checkout $BRANCH &> /dev/null
    cd $OLDPWD
}

# commit to spec docs
function cmtsd()
{
    cp $1 $SPECDOCS/models
    cd $SPECDOCS/models
    git add $1
    git commit
    cd $OLDPWD
}

# push spec docs
function pushsd()
{
    cd $SPECDOCS
    git push
    cd $OLDPWD
}

# make feature and tracking
function mkft()
{
    cd $SPECDOCS
    git checkout -b $1
    git push -u origin $1
    cd $OLDPWD
}

# pull SPDSAPISwaggerModels
function pspds()
{
    cd $SPDS
    git checkout APIG
    git pull
    cd $OLDPWD
}

# get a file from SPDS
function gspds()
{
    cd $SPDS/markdown
    echo 'Retrieved:'
    for file in `ls | grep "$1"`
    do
        echo "    - $file"
        cp $file $OLDPWD
    done
    cd $OLDPWD
}

# pull selling partner api docs and models
function pspapi()
{
    WD=`pwd`
    cd $SPAPID
    git checkout main
    git pull
    cd $SPAPIM
    git checkout main
    git pull
    cd $WD
}

# display the name of the current branch of SpectrumDocs
function brsd()
{
    cd $SPECDOCS
    git branch
    cd $OLDPWD
}

# remove branch from SpectrumDocs
function rmft()
{
    cd $SPECDOCS
    git branch -D $1 && git push origin --delete $1
    cd $OLDPWD
}

# git status SpectrumDocs
function gstsd()
{
    cd $SPECDOCS
    git status
    cd $OLDPWD
}

# checkout branch in SpectrumDocs
function ckoutsd()
{
    cd $SPECDOCS
    git checkout $1
    cd $OLDPWD
}
